### ISSUE TITLE
its incredible!

### ISSUE THREAD

**Issue by erfanbashar1q** [Bluemoondragon07/Obsidian-Serenity#1]
just this

**Comment by erfanbashar1q** [comment]
and kindly I wanna report another thing that is also related to the callout;

when the auto fadeout inactivated line feature is activated, in the callout that contains a PDF file in it even by hovering the PDF is not unfade; I know that it is based on the line and text, it is just a suggestion that it could be better to have a option that if we hover over the PDF or any attachment it will be unfaded; I do not know is it possible technically or not.

**Comment by erfanbashar1q** [comment]
and the third one;

it is a bug, as I hover over the navigation forward or backward that are located in the tab bar; if I wanna click on the navigate backward it is not possible, because as soon as I put my mouse near it the tab bar is hided and the ribbon is activated; so the usage of navigate backward in the tab bar technically is not possible.
<img width="1512" alt="Screenshot 2023-04-12 at 22 42 53" src="https://user-images.githubusercontent.com/116307599/231580087-66487bc4-e0d4-4c13-b6cd-7ab1416ca963.png">

**Comment by erfanbashar1q** [comment]
the other one is related to the Tasks plugin; in the reading mode the date is not shown in a correct way.

<img width="659" alt="Screenshot 2023-04-12 at 22 47 18" src="https://user-images.githubusercontent.com/116307599/231581042-344c36c0-a05d-40db-a5fc-718953741fef.png">

as you can see the last date is not correctly shown.

**Comment by erfanbashar1q** [comment]
this is my question really I don't know is it a bug or not; is it intentional style that the hashtag part (#) and the name of the tag have different colour for the tasks plugin?
<img width="716" alt="Screenshot 2023-04-12 at 22 49 32" src="https://user-images.githubusercontent.com/116307599/231581501-46701463-0887-482b-b25f-eeddfeb452c7.png">
this is in editing mode; but I think it is not intentional because other tags and also in the reading mode it is disappeared!

BTW, thanks a lot; the first view of the theme for me was incredible; I hope you continue its development.

**Comment by Bluemoondragon07** [comment]
Glad you like the theme :)

1. The blockquote line not extending to the list items is something I forgot to add. I will fix this in the next update.
2. I think it will be possible to make certain items in Edit Mode full opacity on hover. I will work on this.
3. The navigation bar issue can be fixed by adding extra padding to the left of the titlebar. I will fix this also! But if you want to navigate back and forth right now with hotkeys, you can use `ctrl + alt + left-arrow` or `ctr + alt + right-arrow` also.
4. I don't use the Tasks plug-in, so I'm not sure why it's doing that. I'll install the plug-in for some testing, though.
5. As for the last one with the tags, I actually noticed that, but haven't found a solution. It only affects tags contained within lists, so I think the list messes up the `nth-child` styling. It works in reading mode, though, so I think I might leave it that way unless I find another fix.

**Comment by therazman** [comment]
Hey,
First of all, incredible theme indeed!
Since we're on topic of discussing bugs here, I'm not going to create another issue.
![CleanShot 2023-04-19 at 22 54 26](https://user-images.githubusercontent.com/4894372/233185812-1b8732b8-4637-4e44-9621-558d9caea140.png)
The task checkboxes are tiny, I'm not sure if it's on purpose, but I think they could be more prominent.
Also, it seems it's the theme's job is to support custom statuses. As you can see, they are all displayed as done.
![CleanShot 2023-04-19 at 23 00 38](https://user-images.githubusercontent.com/4894372/233186789-19dee142-6502-4682-81e7-32db5c71dbd4.png)

**Comment by therazman** [comment]
Also, I want to share a modification I made to the settings pane to make things more compact. I have many plugins, and I found it hard to scroll through all of them.
```CSS
/* settings pane tighter list items */
.horizontal-tab-nav-item, .vertical-tab-nav-item {
    padding: 0.5em 1em;
}

.vertical-tab-header-group-title {
    font-size: var(--font-ui-smaller);
    text-align: left;
    border-bottom: none;
}
```
![Untitled-1](https://user-images.githubusercontent.com/4894372/233189294-0f67a01f-08b1-4bf7-a692-4dd68b9394ad.png)

**Comment by Bluemoondragon07** [comment]
Thanks for the feedback, @therazman! The checkbox size was something I tweaked as an experiment and I forgot to change it back before I updated the theme...so yeah, that will definitely go in the next update.

And as for the checkbox states, I wasn't planning on adding them, but since you mentioned it, I think I'll try to squeeze that into the next update as well.

And I like your version of the sidebars. Is it okay if I use it for a style settings option?

**Comment by Bluemoondragon07** [comment]
@erfanbashar1q, I believe all of these have been fixed by the latest update.
- elements are now full opacity on hover in edit mode
- blockquote line is fixed
- navigation bar is in a better position to click

And I believe the appearance issue with the Tasks plug-in was from Dataview styling that made the font smaller. I have changed this code, and hopefully that fixed it. If it didn't, let me know and I'll look deeper into it.

Thanks for helping me improve the theme, I really appreciate it!

**Comment by Bluemoondragon07** [comment]
@therazman, I added custom checkboxes in the latest update! The syntax is the same as Minimal's.

I also added your compact settings snippet as a setting under the `Modals` heading. Thanks for helping me improve the theme, enjoy the update!
