### ISSUE TITLE
Questions about fonts

### ISSUE THREAD

**Issue by outwhy** [Bluemoondragon07/Obsidian-Serenity#7]
Hello, I am using your theme, thank you. I have found some problems in using it, I am a Chinese user and have set my own interface font for Obsidian (PingFang SC), but the Chinese font in the interface is not PingFang SC font, the English font is successfully displayed as PingFang SC, can there be a solution for it, thank you for watching!

**Comment by Bluemoondragon07** [comment]
Hello! Unfortunately, I don't know a lot of Chinese, so I may not be able to come to a solution. 

One thing I know might work is instead of typing 'PingFang SC' , if there is an alternate Chinese name for the font, type that instead. Or, type both the English version of the font and the Chinese version, separated by a comma.

For example, I see some fonts in css files like, `font-family: "Microsoft Yahei","微软雅黑", sans-serif`. Sometimes the Chinese name is required for the font to work.

If it doesn't work, let me know and I'll see what I can do.
